### ISSUE TITLE
ks0108 192x64

### ISSUE THREAD

**Issue by clear-sky** [bratoff/I2C_graphical_LCD_display#1]
hi 
thanks for this great code
i have ks0108 192x64 is that possible to use this code or i should use two pcf8574?

**Comment by bratoff** [comment]
Hi,
The KS0108 operates in banks of 64x64. On the 128x64, there's a separate CS/ pin for each bank but all other signals are shared.  It wouldn't take much to expand the code to add the 3-bank case.  The changes would be:
- Expand the frame buffer
- Adjust the calculations that determine the bank from the X coordinate
- Change handling of CSA and CSB to the way the 192x64 interprets it.

If you want to give that a try, please wrap the changes in a conditional compile and then send me a PR so I can add your changes to the base library. 

Another port expander won't help because the data and control lines are shared across all banks.  Code changes are needed.

Good luck - let me know how it goes!
